#########################################################################
# Title:            Community: HomeAssistant                            #
# Author(s):        fugume                                              #
# URL:              https://github.com/Cloudbox/Community               #
# Docker Image(s):  thraxis/lazylibrarian-calibre                       #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Setting CloudFlare DNS Record"
  include_role:
    name: cloudflare-dns
  vars:
    record: homeassistant
  when: cloudflare_enabled

- name: Stop and remove any existing container
  docker_container:
    name: homeassistant
    state: absent

- name: Create home assistant directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/homeassistant

- name: Create and start container
  docker_container:
    name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable 
    pull: yes
    published_ports:
      - "127.0.0.1:8123:8123"
    env:
      TZ: "{{ tz }}"
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      VIRTUAL_HOST: "homeassistant.{{ user.domain }}"
      VIRTUAL_PORT: "8123"
      LETSENCRYPT_HOST: "homeassistant.{{ user.domain }}"
      LETSENCRYPT_EMAIL: "{{ user.email }}"
    volumes:
      - "/opt/homeassistant:/config"
      - "/mnt:/mnt"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - homeassistant
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
